/**
 * Long-form editorial content. Each guide becomes a static article page, an
 * entry in the blog/news sitemaps, an RSS/Atom item, and Article JSON-LD.
 * Body is authored as an array of blocks so it can be rendered to HTML for the
 * site and to plain text for the AI training files.
 */

export const guides = [
  {
    slug: "memorial-day-golf-cart-sales-event-guide",
    question: "When is the Memorial Day golf cart sales event and what is discounted?",
    answer: "The Memorial Day Golf Cart Sales Event runs May 15 to June 2. Every new and used cart in stock carries event pricing, with 0% APR for 48 months on approved credit, same-day trade appraisals and delivery available. It is the deepest in-stock pricing and the widest selection of the year.",
    title: "The Complete Guide to the Memorial Day Golf Cart Sales Event",
    description:
      "Everything to know before you buy during the Memorial Day Golf Cart Sales Event: what is discounted, how event financing works, and how to lock in Memorial Day pricing.",
    date: "2026-05-18",
    updated: "2026-05-18",
    category: "Sales Event",
    tags: ["memorial day golf cart sales event", "memorial day golf cart sale", "buying guide"],
    readingMinutes: 7,
    body: [
      { h2: "Why the Memorial Day is the best week of the year to buy a golf cart" },
      { p: "Memorial Day sits at the exact midpoint of the golf cart selling season. Spring inventory has landed, the next model year is still months away, and dealers need floor space. That combination is why the Memorial Day Golf Cart Sales Event consistently produces the deepest in-stock pricing of the summer — deeper, in most years, than Memorial Day, and without the September wait." },
      { p: "The event runs from May 15 through June 2. Event pricing applies to every cart in stock at all 15 Memorial Day Golf Carts locations: new, used, electric, gas, lifted, and street legal LSV models alike." },
      { h2: "What is actually discounted during the Memorial Day event" },
      { list: [
        "Current model-year new carts, which carry the largest reductions because they are being cleared ahead of the changeover.",
        "Reconditioned trade-ins, which are priced to move quickly during the holiday week.",
        "Lithium battery upgrades and lift kits when bundled with a cart purchase.",
        "Accessory packages — enclosures, sound systems, rear seat kits and light kits — added at the time of sale.",
      ] },
      { h2: "How 0% APR financing works during the sale" },
      { p: "0% APR for 48 months is available on approved credit through six lending partners. On a $12,000 cart that works out to $250 per month with no interest charged over the term. Most partners run a soft-pull prequalification that does not affect your credit score, and approvals typically come back the same day." },
      { p: "Bring a driver's license and proof of income. If you are financing as a business — a resort, HOA, campground or club — Univest Capital and DLL Financial handle commercial paper and fleet purchases." },
      { h2: "How to lock in Memorial Day pricing" },
      { list: [
        "Browse live inventory on this site — it refreshes every morning at 1:30 AM Eastern directly from the dealership system.",
        "Call 844-456-2228 with the stock you want. A deposit holds event pricing even if delivery is scheduled after June 2.",
        "Ask for the trade appraisal at the same time; trade value stacks on top of event pricing.",
        "Confirm delivery. Delivery is quoted to your address, and most locations can deliver within a few days.",
      ] },
      { h2: "New or used during the event?" },
      { p: "New carts carry a full factory warranty and the current battery chemistry, which matters most on electric models — a new lithium pack should give 8 to 10 years of service. Used carts from the event floor have been reconditioned and inspected, and the battery year is published on every vehicle page on this site so you can judge remaining pack life before you call." },
      { p: "If the cart will see daily neighborhood or beach use, a new lithium model bought at event pricing is usually the better long-run value. If it will be a second cart or see seasonal use only, a reconditioned trade-in during the Memorial Day sale is hard to beat on price." },
    ],
  },
  {
    slug: "electric-vs-gas-golf-carts",
    question: "Should you buy an electric or a gas golf cart?",
    answer: "Electric for almost everyone: cheaper to run, near-silent, far less maintenance, and permitted where gas carts are banned. Gas if the cart runs all day with no chance to charge, the ground is steep, or the property is large enough that range matters more than running cost.",
    title: "Electric vs Gas Golf Carts: How to Choose in 2026",
    description:
      "A practical comparison of electric and gas golf carts — range, running cost, maintenance, noise and resale — to help you pick the right cart during the Memorial Day sales event.",
    date: "2026-05-10",
    updated: "2026-05-10",
    category: "Buying Guide",
    tags: ["electric golf carts", "gas golf carts", "buying guide", "lithium"],
    readingMinutes: 6,
    body: [
      { h2: "The short answer" },
      { p: "For neighborhood, resort, beach and golf community use, an electric cart — ideally lithium — is the right choice for most buyers. For very large acreage, hunting, hilly terrain or all-day continuous running with no chance to charge, gas still wins." },
      { h2: "Running cost" },
      { p: "A full charge on a 48V electric cart costs roughly $0.50 to $1.50 depending on local electricity rates, and delivers 25 to 40 miles on lead-acid or 45 to 60 miles on lithium. A gas cart burns about a gallon every 30 to 40 miles. Over a typical season, electric running costs are a small fraction of gas." },
      { h2: "Maintenance" },
      { list: [
        "Electric with lithium: effectively no scheduled battery maintenance, no watering, no engine service. Brakes, tires and the charger are the wear items.",
        "Electric with lead-acid: monthly water checks and terminal cleaning; pack replacement every 4 to 6 years.",
        "Gas: oil changes, air and fuel filters, spark plugs, belts and carburetor service, plus fuel stabilizer for winter storage.",
      ] },
      { h2: "Noise, emissions and where you can drive" },
      { p: "Many golf communities, campgrounds, gated neighborhoods and beach towns restrict or ban gas carts outright on noise and emissions grounds. Confirm local rules before buying gas. Electric carts are near silent and are accepted everywhere carts are permitted." },
      { h2: "Lithium versus lead-acid" },
      { p: "Lithium (LiFePO4) packs run 3,000 to 5,000 cycles against 500 to 1,000 for lead-acid, weigh roughly half as much, charge in 3 to 5 hours instead of 8 to 10, and hold voltage to the end of discharge so the cart does not slow as the pack drains. The purchase premium is usually recovered within one pack replacement cycle." },
      { h2: "Resale" },
      { p: "Lithium electric carts hold value best, followed by gas carts in low-hour condition, then lead-acid electric — where the buyer is always pricing in an imminent pack replacement. If resale matters, buy lithium." },
    ],
  },
  {
    slug: "street-legal-golf-carts-lsv-guide",
    question: "What makes a golf cart street legal?",
    answer: "A street legal cart is a Low Speed Vehicle under FMVSS 500. It must reach 20 to 25 mph and carry headlights, tail and brake lights, turn signals, reflectors, two mirrors, a parking brake, a DOT windshield, seat belts at every seat, and a VIN. It then needs titling, registration and insurance.",
    title: "Street Legal Golf Carts and LSVs: Requirements by State",
    description:
      "What separates a street legal LSV from a standard golf cart, the federal equipment list, and how titling and registration differ across the states we serve.",
    date: "2026-05-05",
    updated: "2026-05-05",
    category: "Legal",
    tags: ["street legal golf carts", "LSV", "registration", "regulations"],
    readingMinutes: 6,
    body: [
      { h2: "Golf cart, LSV, or NEV?" },
      { p: "A standard golf cart tops out under 20 mph and is not federally regulated as a motor vehicle. A Low Speed Vehicle (LSV), sometimes called a Neighborhood Electric Vehicle, reaches 20 to 25 mph and is regulated under Federal Motor Vehicle Safety Standard 500. LSVs get a VIN, and in most states they are titled, registered and insured like a car." },
      { h2: "Federal equipment required on an LSV" },
      { list: [
        "Headlights, tail lights and stop lights",
        "Front and rear turn signal lamps",
        "Red reflex reflectors — one on each side and one at the rear",
        "An exterior mirror on the driver side plus either an interior mirror or a passenger-side exterior mirror",
        "A parking brake",
        "A windshield meeting the federal glazing standard",
        "A Vehicle Identification Number",
        "A Type 1 or Type 2 seat belt at each designated seating position",
      ] },
      { h2: "How the states we serve differ" },
      { p: "Requirements vary and change; always confirm with your state DMV or local municipality before purchase. In broad terms: Delaware, Florida, North Carolina and South Carolina all register LSVs for road use on streets posted at or below 35 mph, with local exceptions along the beaches. Pennsylvania and New Jersey are more restrictive — carts are generally limited to private property, permitted communities and specific municipal ordinances. Virginia, Indiana and Vermont permit local ordinance-based operation that differs town by town." },
      { p: "Memorial Day Golf Carts sells LSV-equipped carts and can bring an existing cart up to LSV specification. Every vehicle page on this site shows whether that specific cart is street legal, and the inventory search has a street legal filter." },
      { h2: "Insurance" },
      { p: "Where an LSV is registered for road use, liability insurance is normally required, and most auto carriers will add an LSV to an existing policy inexpensively. Even where insurance is not required, coverage is worth carrying — carts are frequently stolen and are rarely covered by homeowners policies once they leave the property." },
    ],
  },
  {
    slug: "golf-cart-battery-guide",
    question: "How long does a golf cart battery last and what does it cost?",
    answer: "A lead-acid pack lasts four to six years or 500 to 1,000 cycles and costs $900 to $1,800 to replace. A lithium pack lasts eight to ten years or 3,000 to 5,000 cycles and costs $2,200 to $4,000. On a cart you intend to keep, lithium is usually recovered once over its life.",
    title: "Golf Cart Batteries: Lithium, AGM and Lead-Acid Compared",
    description:
      "How to read a battery pack spec, what lifespan to expect from each chemistry, and how to judge the battery on a used golf cart before you buy.",
    date: "2026-05-28",
    updated: "2026-05-28",
    category: "Maintenance",
    tags: ["golf cart batteries", "lithium", "maintenance", "used golf carts"],
    readingMinutes: 5,
    body: [
      { h2: "Reading the spec on a vehicle page" },
      { p: "Every electric cart on this site publishes its pack voltage, cell voltage, amp hours, chemistry, brand, battery year and remaining battery warranty. Pack voltage — 36V, 48V, 72V — sets the cart's power. Amp hours set the range. Battery year tells you how much life is left." },
      { h2: "Expected life by chemistry" },
      { list: [
        "Lithium iron phosphate (LiFePO4): 8 to 10 years, 3,000 to 5,000 cycles, no maintenance, 3 to 5 hour charge.",
        "AGM sealed lead-acid: 4 to 6 years, 600 to 1,200 cycles, no watering, 6 to 8 hour charge.",
        "Flooded lead-acid: 4 to 6 years, 500 to 1,000 cycles, monthly watering required, 8 to 10 hour charge.",
      ] },
      { h2: "Judging the battery on a used cart" },
      { p: "Ask for the battery year first — a lead-acid pack older than four years should be treated as a near-term replacement cost of $900 to $1,800. On a test drive, watch for the cart slowing noticeably on a hill or after 20 minutes of running; that is voltage sag and it points to a tired pack. On flooded packs, check for corrosion at the terminals and confirm the water level is above the plates." },
      { h2: "Charging habits that extend pack life" },
      { list: [
        "Charge after every use rather than waiting for the pack to run low, on any chemistry.",
        "Never store a lead-acid pack discharged over winter — it will sulfate and lose capacity permanently.",
        "Leave a lithium pack at roughly half charge for long storage, and keep the disconnect off.",
        "Use the charger matched to the pack. A lead-acid charger on a lithium pack will not charge it correctly.",
      ] },
    ],
  },
  {
    slug: "golf-cart-buying-checklist",
    question: "What should you check before buying a golf cart?",
    answer: "Six things: the battery year and chemistry, whether the cart is street legal or can be made so, seat count against how you will actually use it, lift and tires against your terrain, what the total price includes, and who services it afterwards. Ask all six before you agree a price.",
    title: "Golf Cart Buying Checklist: 12 Questions to Ask Before You Sign",
    description:
      "A dealer-side checklist covering warranty, battery age, street legality, delivery, trade-in and financing so nothing gets missed during a sales event purchase.",
    date: "2026-05-20",
    updated: "2026-05-20",
    category: "Buying Guide",
    tags: ["buying guide", "checklist", "golf cart warranty"],
    readingMinutes: 4,
    body: [
      { h2: "Before you shop" },
      { list: [
        "How many passengers do you need to seat regularly — 2, 4, 6 or 8?",
        "Will the cart be driven on public roads? If yes, you need an LSV, not a standard cart.",
        "What terrain — flat pavement, sand, grass, or hills? Hills and sand favor lifted carts and higher pack voltage.",
        "Where will it charge? Electric carts need a standard outlet within reach of where the cart parks.",
      ] },
      { h2: "On the lot" },
      { list: [
        "What is the battery year and chemistry, and how much battery warranty remains?",
        "What warranty covers the cart itself, and what is specifically excluded?",
        "Is this cart street legal as it sits, and does it have a VIN and title?",
        "What is the total out-the-door price including freight, prep, tax and any accessories?",
      ] },
      { h2: "Closing" },
      { list: [
        "What is my trade worth, and does trade value stack on top of event pricing? (At Memorial Day Golf Carts it does.)",
        "What is the monthly payment at 0% APR for 48 months, and what does prequalification require?",
        "When can it be delivered, and is delivery included?",
        "Who services the cart afterward, and where is the nearest service location?",
      ] },
      { p: "Call 844-456-2228 with this list in hand and any Memorial Day Golf Carts location will walk it with you line by line." },
    ],
  },

  {
    slug: "lithium-vs-lead-acid-golf-cart-batteries",
    question: "Is a lithium golf cart battery worth the extra money?",
    answer:
      "For a cart driven regularly, yes. Lithium gives 45 to 60 miles per charge against 25 to 40, lasts three to five times as many cycles, weighs half as much and needs no watering. It costs roughly twice as much up front and is recovered once over the life of the cart.",
    title: "Lithium vs Lead-Acid Golf Cart Batteries",
    description:
      "A direct comparison of lithium and lead-acid golf cart batteries: range, cycle life, replacement cost, weight, charging behaviour, cold weather and which one actually pays back.",
    date: "2026-05-12",
    updated: "2026-05-12",
    category: "Batteries",
    tags: ["lithium vs lead-acid golf cart batteries", "golf cart battery", "lithium golf cart", "golf cart battery cost"],
    readingMinutes: 8,
    body: [
      { h2: "The short answer" },
      { p: "If the cart is driven most weeks, buy lithium. If it is driven a few weekends a year, buy lead-acid and put the difference in your pocket. Everything below is the arithmetic behind that." },
      { h2: "How do the two chemistries compare?" },
      { table: {
        caption: "Lithium (LiFePO4) versus lead-acid golf cart packs, 48V",
        headers: ["", "Lead-acid (flooded)", "AGM", "Lithium (LiFePO4)"],
        rows: [
          ["Range per charge", "25 – 40 miles", "30 – 45 miles", "45 – 60 miles"],
          ["Cycle life", "500 – 1,000", "600 – 1,200", "3,000 – 5,000"],
          ["Service life", "4 – 6 years", "5 – 7 years", "8 – 10 years"],
          ["Replacement cost", "$900 – $1,800", "$1,400 – $2,200", "$2,200 – $4,000"],
          ["Pack weight", "300 – 400 lb", "300 – 400 lb", "120 – 180 lb"],
          ["Charge time", "8 – 10 hours", "6 – 8 hours", "3 – 5 hours"],
          ["Partial charging", "Damages the pack", "Damages the pack", "No harm"],
          ["Watering and cleaning", "Monthly", "None", "None"],
          ["Speed as pack drains", "Falls off noticeably", "Falls off", "Holds to near empty"],
        ],
      } },
      { h2: "What does each pack really cost over ten years?" },
      { p: "Take a cart driven three times a week — roughly 150 cycles a year. Lead-acid at 750 cycles is a pack every five years, so two replacements inside ten years: about $1,400 up front plus $2,800 in replacements, call it $4,200. Lithium at 4,000 cycles does not need replacing in that window: about $3,000 and done. The lithium cart is cheaper by year seven, and it was the better cart every day in between." },
      { p: "Now take a cart driven twelve weekends a year — about 30 cycles. Lead-acid will die of age rather than cycles, at maybe eight years. One pack, $1,400, and you never pay again. The lithium premium buys you range and weight you are not using. Buy lead-acid." },
      { h2: "Why does lithium hold its speed?" },
      { p: "Lead-acid voltage sags under load and falls as the pack depletes, and a golf cart controller translates voltage into speed. So a lead-acid cart is slower up the last hill of the day than the first. A lithium pack holds voltage nearly flat until it is almost empty, then cuts off. Most people notice this before they notice the range." },
      { h2: "Can you retrofit lithium into an older cart?" },
      { p: "Usually, and it is one of the better upgrades on a sound cart. You need a drop-in 48V LiFePO4 pack sized to the tray, a compatible charger, and on some carts a controller or converter change because lithium packs sit at a slightly different voltage. Budget $2,200 to $4,000 fitted. It is not worth doing on a cart with a tired motor or a cracked frame — see the <a href=\"/guides/golf-cart-buying-checklist/\">buying checklist</a> first." },
      { h2: "What about cold weather?" },
      { p: "This is lithium's real weakness. Below freezing a LiFePO4 pack loses usable capacity, and below about 0 °C most packs will not accept a charge at all without an internal heater. If the cart winters in an unheated barn in Pennsylvania, that matters and you should ask specifically about a heated pack. In Florida it is irrelevant." },
      { h2: "How do you read a battery year on a listing?" },
      { p: "We publish the pack year and chemistry on every used listing, which most dealers do not. Treat a lead-acid pack past four years as a replacement due within two, and price accordingly. A lithium pack from the last five years has most of its life ahead of it and should be valued as such." },
      { h2: "Which should you buy?" },
      { list: [
        "Driven most weeks, or hills, or you keep carts a long time — lithium.",
        "Fleet or rental with a two-shift duty cycle — lithium, because it tolerates partial charges between shifts.",
        "A few weekends a year, or the lowest purchase price is the constraint — lead-acid.",
        "Cart lives unheated in a northern winter — lead-acid, or lithium with a heated pack.",
      ] },
      { p: "We have lithium and lead-acid carts on the floor now: browse <a href=\"/inventory/lithium/\">lithium golf carts</a>, or see everything at <a href=\"/inventory/electric/\">electric golf carts</a>. Call 844-456-2228 if you want a specific pack size." },
    ],
    faq: [
      { q: "How long does a lithium golf cart battery last?", a: "Three to five thousand charge cycles, which for most private owners is eight to ten years of ordinary use. Lead-acid gives five hundred to a thousand cycles, or four to six years." },
      { q: "How much does a lithium golf cart battery cost?", a: "$2,200 to $4,000 for a 48V LiFePO4 pack fitted, against $900 to $1,800 for lead-acid. The lithium pack normally outlives two or three lead-acid packs, which is where it earns the difference back." },
      { q: "Can you charge a lithium golf cart battery part way?", a: "Yes, with no harm at all — plugging in for an hour between trips costs a lithium pack nothing. Lead-acid is degraded by exactly that habit and wants a full charge cycle every time." },
      { q: "Do lithium golf carts go faster?", a: "Not usually a higher top speed, but they hold their top speed until the pack is nearly empty, where a lead-acid cart slows as it depletes. In practice a lithium cart feels faster on the last run of the day." },
      { q: "Is lithium safe in a golf cart?", a: "LiFePO4, the chemistry used in golf carts, is the most thermally stable lithium chemistry in common use and is not the same as the cobalt cells in phones and laptops. Packs sold for carts carry a battery management system that prevents over-charge and over-discharge." },
    ],
  },
  {
    slug: "off-road-and-lifted-golf-carts",
    question: "What is an all terrain golf cart, and do you need one?",
    answer:
      "An all terrain golf cart is a lifted cart on knobby off-road tires, riding three to six inches higher than standard with firmer suspension. You need one if the cart will cross soft sand, wet grass, mud or gravel. On pavement and turf a standard cart is quieter, smoother and goes further.",
    title: "Off-Road, Lifted and 4x4 Golf Carts Explained",
    description:
      "How lift height, tire type and four-wheel drive actually differ, what each one solves, what they cost you in range and ride, and how to specify a cart for sand, trail or farm use.",
    date: "2026-05-14",
    updated: "2026-05-14",
    category: "Off-Road",
    tags: ["off-road golf carts", "lifted golf carts", "4x4 golf carts", "all terrain golf cart", "street legal all terrain carts"],
    readingMinutes: 7,
    body: [
      { h2: "Three different problems" },
      { p: "People use \"off-road\", \"lifted\" and \"4x4\" interchangeably, and they are not the same thing. Lift solves ground clearance. Tires solve traction on loose surfaces. Four-wheel drive solves traction when weight transfers off a wheel. Buying the wrong one is how you end up with a tall cart that still gets stuck." },
      { table: {
        caption: "What each modification actually solves",
        headers: ["Modification", "Solves", "Costs you", "Buy it when"],
        rows: [
          ["3 inch lift", "Dragging on grass, gravel, kerbs", "Slightly higher step-in", "Grass, gravel, packed sand"],
          ["5 – 6 inch lift", "Dragging in ruts and soft sand", "Step-in height, some stability", "Beach, rutted tracks, trail"],
          ["All-terrain tires", "Wheels spinning on loose ground", "5 – 15% of range, road noise", "Sand, mud, wet grass"],
          ["4x4 drivetrain", "Wheels spinning when weight shifts", "Up to 15% range, price, servicing", "Soft dune sand, clay mud, steep wet ground"],
        ],
      } },
      { h2: "How much lift do you actually need?" },
      { p: "Three inches clears 12 inch wheels and handles most grass, gravel and packed sand. Five to six inches clears 14 inch wheels and is what soft beach sand and rutted tracks genuinely require. Past six inches you are buying appearance and paying for it in step-in height, a higher centre of gravity and a driveline running at a steeper angle than it was designed for." },
      { h2: "Are all-terrain tires worth the range penalty?" },
      { p: "On loose ground, easily. A turf tire has a shallow wide pattern designed not to mark a fairway, and on sand it skates. An all-terrain tire has deep open lugs that bite. The cost is five to fifteen percent of your range from rolling resistance and rotating weight, plus noticeably more noise on pavement. Pick for the worst surface the cart will see, not the average." },
      { h2: "Does anyone need a 4x4 golf cart?" },
      { p: "Two cases, genuinely: soft dune sand, and clay mud after rain. In both, a 2x4 cart with all the clearance and tread in the world will still sit and spin one wheel. Everywhere else — paved paths, turf, packed gravel, hard-packed beach — a lifted 2x4 on all-terrain tires does the job for considerably less money and less to go wrong." },
      { p: "Four-wheel-drive carts are a small share of what any dealer floors. Our <a href=\"/inventory/4x4/\">4x4 golf carts</a> page shows real stock rather than a catalogue, so it is often thin; we source them to order." },
      { h2: "Can an off-road cart also be street legal?" },
      { p: "Yes, and many of ours are. A lift and knobby tires do not disqualify a cart from Low Speed Vehicle status — the LSV requirements are about lighting, mirrors, belts, a windshield, a VIN and a 20 to 25 mph top speed, not about ride height. Watch the speedometer calibration though: larger tires make a cart travel further per motor revolution, which can push a 25 mph cart past the LSV ceiling. See <a href=\"/inventory/street-legal/\">street legal golf carts</a> and the <a href=\"/guides/street-legal-golf-carts-lsv-guide/\">LSV guide</a>." },
      { h2: "What breaks first on an off-road cart?" },
      { list: [
        "Bushings and shock bodies, from the extra travel and the extra unsprung weight.",
        "Rear axle seals, once sand gets past them — rinse the underside after beach use.",
        "The battery pack, if you run soft sand regularly. Sand is the hardest surface there is on a pack; size the battery to the terrain, not the spec-sheet mileage.",
        "CV boots and driveline angles on carts lifted past six inches.",
      ] },
      { p: "Our <a href=\"/guides/golf-cart-tires-and-suspension/\">tire and suspension guide</a> has the size-to-lift table and the maintenance intervals that actually matter." },
      { h2: "How to specify one" },
      { p: "Start from the surface. Hard-packed and paved: standard cart, turf tires. Grass and gravel: three inch lift, 12 inch all-terrain. Beach and trail: five to six inch lift, 14 inch all-terrain, and size the pack up one step. Dune sand or clay mud: add four-wheel drive. Then browse <a href=\"/inventory/all-terrain/\">all-terrain golf carts</a> or <a href=\"/inventory/lifted/\">lifted golf carts</a>, or call 844-456-2228 and describe the ground." },
    ],
    faq: [
      { q: "What is an all terrain golf cart?", a: "A golf cart on knobby off-road tires rather than smooth turf tires, almost always with a three to six inch lift and firmer suspension, so it can cross sand, mud, wet grass and loose gravel without dragging or spinning." },
      { q: "How much does an all terrain golf cart cost?", a: "In our current stock, lifted all-terrain carts run roughly $7,000 used to $15,500 for a new lifted lithium model built to street-legal specification. The lift and tire package itself is typically $1,200 to $2,500 of that." },
      { q: "Are all terrain golf carts street legal?", a: "They can be. Lift and tires do not affect Low Speed Vehicle eligibility, which is about lighting, mirrors, seat belts, a windshield, a VIN and a 20 to 25 mph top speed. Many of our lifted carts are already built to LSV specification." },
      { q: "Is a lifted golf cart less stable?", a: "Marginally, because the centre of gravity rises. Up to about six inches with a matched suspension package the difference is not noticeable in normal use. Past that, on side slopes, it becomes real." },
      { q: "Do I need 4x4 for the beach?", a: "For hard-packed sand below the tide line, no — a lifted 2x4 on all-terrain tires is enough. For soft dry dune sand, yes. That is the single clearest case for four-wheel drive on a golf cart." },
    ],
  },
  {
    slug: "golf-cart-tires-and-suspension",
    question: "What tires and suspension should a golf cart have?",
    answer:
      "Match the tire to your worst surface and the lift to the tire. Turf tires for pavement and grass, all-terrain for sand and mud, street tires for an LSV driven on road. A 12 inch wheel needs about three inches of lift; a 14 inch wheel needs five to six.",
    title: "Golf Cart Tires and Suspension: A Sizing Guide",
    description:
      "Tire types, wheel sizes, the lift each one needs, what larger tires do to speed and range, suspension upgrades that are worth it, and the maintenance intervals that matter.",
    date: "2026-05-16",
    updated: "2026-05-16",
    category: "Maintenance",
    tags: ["golf cart tires", "golf cart suspension", "golf cart lift kit", "golf cart tire size"],
    readingMinutes: 7,
    body: [
      { h2: "Which tire type do you need?" },
      { p: "There are three, and they are not interchangeable. Choose for the worst surface the cart will regularly see." },
      { table: {
        caption: "Golf cart tire types compared",
        headers: ["Type", "Best on", "Poor on", "Road noise", "Range effect"],
        rows: [
          ["Turf", "Fairway, lawn, pavement", "Sand, mud", "Very low", "Baseline"],
          ["Street / DOT", "Paved road, LSV use", "Anything loose", "Low", "Baseline to +5%"],
          ["All-terrain", "Sand, mud, gravel, trail", "Nothing much, but noisy", "High", "−5 to −15%"],
        ],
      } },
      { p: "If the cart is registered as a Low Speed Vehicle and driven on public roads, check whether your state requires a DOT-rated tire. Several do, and an all-terrain tire is often not DOT rated." },
      { h2: "What lift does each wheel size need?" },
      { table: {
        caption: "Wheel and tire size against required lift",
        headers: ["Wheel", "Typical tire", "Overall diameter", "Lift needed"],
        rows: [
          ["8 inch", "18 x 8.50-8", "18 in", "None (stock)"],
          ["10 inch", "20 x 10-10", "20 in", "None to 2 in"],
          ["12 inch", "23 x 10.50-12", "23 in", "3 in"],
          ["14 inch", "23 x 10-14", "23 in", "3 to 4 in"],
          ["14 inch", "25 x 10-14", "25 in", "5 to 6 in"],
        ],
      } },
      { p: "Overall diameter is what decides clearance, not the wheel size — a 14 inch wheel with a low-profile tire can need less lift than a 12 inch wheel with a tall one. Measure the tire, not the rim." },
      { h2: "What do bigger tires do to speed and range?" },
      { p: "A taller tire travels further per motor revolution, so the cart gains a little top speed and loses low-speed torque and range. Going from a 20 inch to a 23 inch overall diameter is roughly a 15 percent increase in distance per revolution: the speedometer, if there is one, reads low by about that much, and hill-climbing gets noticeably worse. On an LSV this matters legally — the cart must stay under 25 mph." },
      { p: "Some carts can be re-geared or the controller re-programmed to recover the torque. Ask before you fit large tires to a cart that has to pull a grade." },
      { h2: "What suspension upgrades are worth it?" },
      { list: [
        "<strong>Heavy-duty rear leaf springs</strong> — the single best upgrade on a cart that carries four adults or a loaded bed. Cheap and it stops the rear bottoming out.",
        "<strong>Gas shocks front and rear</strong> — worth it on a lifted cart, where the standard dampers are undersized for the travel.",
        "<strong>Long-travel A-arm kits</strong> — genuinely better over rough ground, and the right answer for trail use. Expensive, and overkill for grass.",
        "<strong>Sway bar</strong> — worth considering on a six-passenger cart lifted past five inches.",
      ] },
      { p: "What is generally not worth it: air shocks on a private cart, and any lift past six inches unless the cart is built for it." },
      { h2: "What pressure should golf cart tires run?" },
      { p: "Check the sidewall, but as a guide: turf tires 12 to 18 psi, street tires 18 to 22 psi, all-terrain 10 to 14 psi. Under-inflation is the most common cause of premature shoulder wear on a cart, and it costs range. Check monthly — golf cart tires are small enough that a few psi is a large proportion of the total." },
      { h2: "How long do golf cart tires last?" },
      { p: "Turf tires on a private cart usually die of age, not tread — five to seven years before the rubber hardens and cracks. All-terrain tires on regular sand use wear out in two to four years. Check the date code on the sidewall; a cart with plenty of tread on ten-year-old tires needs tires." },
      { h2: "Alignment after a lift" },
      { p: "A lift changes camber and toe, and a cart driven on a bad alignment will scrub the inside edges off a new set of front tires in a season. Have it set after any lift, and re-check it after the first month. We do this at all our locations — see <a href=\"/service/\">golf cart service</a>." },
      { p: "Browse carts already fitted the way you want: <a href=\"/inventory/lifted/\">lifted golf carts</a>, <a href=\"/inventory/all-terrain/\">all-terrain golf carts</a>, or read the <a href=\"/guides/off-road-and-lifted-golf-carts/\">off-road guide</a>." },
    ],
    faq: [
      { q: "What size tires fit a golf cart without a lift?", a: "Up to about a 20 inch overall diameter, which is typically a 10 inch wheel. Anything taller will rub the body under suspension travel or on full lock, so it needs at least a two to three inch lift." },
      { q: "Do bigger tires make a golf cart faster?", a: "Slightly faster at the top end and noticeably weaker on hills, because a taller tire travels further per motor revolution. It also makes the speedometer read low, which matters if the cart is registered as an LSV with a 25 mph ceiling." },
      { q: "How much does a golf cart lift kit cost?", a: "Typically $400 to $900 for a three to six inch kit, plus $200 to $400 fitting, plus wheels and tires at $600 to $1,400 a set. Budget $1,200 to $2,500 all in for a lift and tire package." },
      { q: "What tire pressure should a golf cart run?", a: "Roughly 12 to 18 psi for turf tires, 18 to 22 for street tires, and 10 to 14 for all-terrain, but always check the sidewall. Check monthly — a few psi is a large proportion of a small tire's total." },
    ],
  },
  {
    slug: "utility-and-fleet-golf-carts",
    question: "What is the difference between a utility cart and a fleet cart?",
    answer:
      "A utility golf cart is a configuration: rear seats replaced by a cargo bed carrying 400 to 1,200 lb. A fleet cart is a purchasing pattern: multiple matched carts specified for uptime rather than features. Many fleets are utility carts, but a resort fleet of six-passenger people-movers is not.",
    title: "Utility and Fleet Golf Carts: How to Specify",
    description:
      "How to specify utility and fleet golf carts for grounds, farm, warehouse, resort and campground use — payload, duty cycle, battery chemistry, spares and commercial financing.",
    date: "2026-05-18",
    updated: "2026-05-18",
    category: "Commercial",
    tags: ["utility golf carts", "fleet golf carts", "commercial golf carts", "resort golf carts"],
    readingMinutes: 6,
    body: [
      { h2: "Utility or passenger?" },
      { p: "Decide what the cart carries. A utility cart trades the rear seat for a bed and hauls tools, feed, turf material or luggage. A six-passenger cart hauls people. A fleet can be either, and large operations usually run both — utility carts for the grounds crew, six-seaters for guest transport." },
      { table: {
        caption: "Utility versus six-passenger configuration",
        headers: ["", "Utility cart", "6-passenger cart"],
        rows: [
          ["Carries", "400 – 1,200 lb of cargo", "6 people"],
          ["Bought by", "Grounds, farm, warehouse, municipal", "Resorts, campgrounds, communities"],
          ["Typical duty", "Full shift, stop-start", "Continuous shuttle runs"],
          ["Battery sizing", "To the shift, not the mileage", "To the route, with margin"],
          ["Wear point", "Rear suspension and bed", "Brakes and tires"],
        ],
      } },
      { h2: "How do you size the battery for commercial use?" },
      { p: "Size to the duty cycle, not the advertised range. A grounds cart doing eight hours of stop-start work with a loaded bed uses far more energy than the mileage suggests, and a resort shuttle that runs from dawn to midnight needs to charge during the day. That second case is the strongest argument for lithium in any fleet: it charges in three to five hours and takes partial charges between runs without damage, where lead-acid is degraded by exactly that pattern." },
      { p: "The rule of thumb we use: single shift with an overnight charge, lead-acid is viable. Two shifts, or any mid-day charging, specify lithium. See the <a href=\"/guides/lithium-vs-lead-acid-golf-cart-batteries/\">battery comparison</a> for the cost arithmetic." },
      { h2: "How many spares does a fleet need?" },
      { p: "Plan on one spare cart per ten in service if downtime costs you revenue, and hold a spare charger, a set of brake shoes and a controller for the platform. Standardising on one model across the fleet is worth more than any individual feature: one parts inventory, one set of procedures, and any cart can be cannibalised for another." },
      { h2: "Can you supply matched multiples?" },
      { p: "Usually. Carts in stock across our locations are singles, so a matched fleet is normally sourced to order — we do that weekly. Give us the count, the seat or bed configuration, the battery chemistry and the delivery date and we will quote against current allocation. Browse what is on the floor now at <a href=\"/inventory/fleet/\">fleet golf carts</a> and <a href=\"/inventory/utility/\">utility golf carts</a>." },
      { h2: "How does commercial financing differ?" },
      { p: "The retail 0% APR programme is for individual buyers. Businesses, resorts and municipalities generally go through Univest Capital or DLL Financial, both of which handle multi-unit purchases, leases and seasonal payment structures that the retail programme does not cover. See <a href=\"/financing/\">financing</a>, and ask for commercial when you call." },
      { h2: "What to specify, in order" },
      { list: [
        "Duty cycle in hours per day, and whether there is a mid-day charging window. This sets the battery chemistry.",
        "Terrain and grades. This sets the motor and the tire.",
        "Payload or seat count. This sets the platform.",
        "Uptime tolerance. This sets the spares holding and whether you need a spare cart.",
        "Whether any cart leaves private property. If so it needs to be a <a href=\"/inventory/street-legal/\">street legal LSV</a>.",
      ] },
      { p: "Call 844-456-2228 and ask for commercial. Tell us the five things above and we will come back with a specification and a price for the whole order rather than a per-cart list price." },
    ],
    faq: [
      { q: "What is a utility golf cart?", a: "A golf cart with the rear seat replaced by a cargo bed, typically carrying 400 to 1,200 lb. Grounds crews, farms, warehouses, campgrounds and municipalities buy them to move tools and material rather than people." },
      { q: "How much can a utility golf cart carry?", a: "Bed capacity on the models we stock runs roughly 400 to 1,200 lb, with towing capacity on top where a hitch is fitted. The practical limit is usually the drivetrain on a grade and the battery over a full shift rather than the bed itself." },
      { q: "What are fleet golf carts?", a: "Carts bought in quantity and specified for uptime rather than features — resort transport, course rental, campground shuttles, community security. In practice that means six-passenger people-movers and utility cargo models, usually standardised on one platform." },
      { q: "Do you offer fleet pricing?", a: "Yes. Multi-unit orders are quoted as a whole rather than at individual list price, and commercial buyers finance through Univest Capital or DLL Financial rather than the retail 0% programme. Call 844-456-2228 and ask for commercial." },
      { q: "Should a fleet use lithium or lead-acid?", a: "Lithium for any fleet running more than one shift or needing to charge mid-day, because it charges in three to five hours and tolerates partial charges. Lead-acid remains viable for a single shift with a full overnight charge." },
    ],
  },
];

export default guides;
